[project]
name = "adasoft"
version = "0.1.2"
description = "Adaptive Soft-Thresholding Algorithm"
authors = [{ name = "Ayoub Ghriss", email = "research@ayghri.me" }]
readme = "README.md"
license = "CC-BY-NC-4.0"
keywords = ["sparsity", "pruning", "neural networks", "structured sparsity", "pytorch"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
requires-python = ">=3.11,<3.14"
dependencies = [
    "torch>=2.10.0,<3.0.0",
    "sparsekit>=0.1.2,<0.2.0",
]

[project.urls]
Homepage = "https://github.com/ayghri/adasoft"
Repository = "https://github.com/ayghri/adasoft"


[tool.poetry]
packages = [{ include = "adasoft", from = "./" }]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
testpaths = ["tests"]
