# Training config for WRN-22-2 on CIFAR-100 (matches SRigL paper settings)

batch_size: 128
epochs: 250
max_steps: null
grad_accumulation_n: 1

## Optimization
optimizer: sgd
weight_decay: 5.0e-4
label_smoothing: 0.0

## Scheduler
scheduler: cosine_annealing_with_warm_up
lr: 0.1
warm_up_steps: 0
gamma: 0.2
step_size: 77
